get  http://localhost:4000/api/user

content-type: application/json

# {
#     "codigo": 4,
#     "nombre": "ejemplo4",
#     "cantidad": 44444,
#     "imagen": "url-sapjdposajd-ap.png",
#     "f_ingreso": "2024-01-18",
#     "f_vencimiento": "2024-03-18",
#     "costo": 60000
# }

# {
#     "nombre":"hola",
#     "cantidad":22,
#     "imagen":"https://th.bing.com/th/id/OIP.AGXIOdkdRHjTmuSUyh9YPAAAAA?rs=1&pid=ImgDetMain"
# }

# {
#     "fecha": "2024-01-18", 
#     "estado": 1, 
#     "total": 20000,
#     "consumidor":1, 
#     "producto":1
# }

# {
#     "id_producto": 1, 
#     "id_factura": 18, 
#     "nombre_producto": "Cafe", 
#     "precio_u": 2000, 
#     "cantidad": 2
# }







